name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
          cache: "npm"

      - run: npm ci

      - run: npm run lint:prettier

      - run: npm run lint:typecheck

      - run: npm run lint:eslint

      - run: npm run build:registry
